version: '3'
name: outbox-pattern

services:

  postgres:
    container_name: postgres
    image: postgres:14.4-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=authentication
    volumes:
      - ./adapters/dbs/sql/schema.sql:/docker-entrypoint-initdb.d/init.sql
    hostname: postgres

  redis:
    container_name: redis
    image: redis:7-alpine
    hostname: redis
    command: redis-server --requirepass password
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=password

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=default
      - RABBITMQ_DEFAULT_PASS=password

  outboxer:
    container_name: outboxer
    build:
      context: .
    volumes:
      - ./test.config.yaml:/config.yaml:ro
    depends_on:
      - postgres
      - redis
      - rabbitmq
    links:
      - postgres
      - redis
      - rabbitmq
    restart: on-failure